### ISSUE TITLE
checklist

### ISSUE THREAD

**Issue by jxchen01** [MMV-Lab/mmv_im2im#73]
https://reviewer.elifesciences.org/author-guide/initial 

- [ ] APA style reference
- [ ] check if all ref fields are completed
- [ ] Methods --> Materials and Methods
- [ ] cover letter (How will your work make others in the field think differently and move the field forward? How does your work relate to the current literature on the topic? Who do you consider to be the most relevant audience for this work? Have you made clear in the letter what the work has and has not achieved?)
- [ ] suggested editors and reviewers
